#index:
#    path: /
#    controller: App\Controller\DefaultController::index
registration:
    path: /
    controller: 'App\Controller\RegistrationController'
index:
    path: /
    controller: 'App\Controller\DefaultController::index'
admin:
    path: /admin
    controller: 'App\Controller\AdminController'

